In [1]:
import pandas as pd
import numpy as np

In [2]:
df_books=pd.read_csv('./bestsellers-with-categories.csv',sep=',',header=0)

In [3]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [6]:
def two_times(value):
    return value*2

In [7]:
df_books['Price'].apply(two_times)

0      16
1      44
2      30
3      12
4      24
       ..
545    16
546    16
547    16
548    16
549    16
Name: Price, Length: 550, dtype: int64

In [8]:
df_books['Price2']=df_books['Price'].apply(lambda x:x*2)

In [9]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Price2  
0        16  
1        44  
2        30  
3        12  
4        24  
..      ...  
545      16  
546      16  
547      16  
548      16  
549      16  

[550 rows x 8 columns]

# apply in two columns

In [11]:
df_books['User Rating2']=df_books.apply(lambda x: x['User Rating']*2 if x['Genre']=='Fiction' else x['User Rating'],axis=1)

In [23]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Price2  User Rating2  
0        16           4.7  
1        44           9.2  
2        30           4.7  
3        12           9.4  
4        24           4.8  
..      ...           ...  
545      16           9.8  
546      16           4.7  
547      16           4.7  
548      16           4.7  
549      16           4.7  

[550 rows x 9 columns]

# EXAMEN

In [13]:
arr=np.array([1,2,3,4])
arr[arr>2]

array([3, 4])

In [14]:
arr = np.array([13, 6, 3, 5, 10])
np.sort(arr)

array([ 3,  5,  6, 10, 13])

In [15]:
df_books.loc[0:10, ['Name', 'Author']]

Name  \
0                       10-Day Green Smoothie Cleanse   
1                                   11/22/63: A Novel   
2             12 Rules for Life: An Antidote to Chaos   
3                              1984 (Signet Classics)   
4   5,000 Awesome Facts (About Everything!) (Natio...   
5       A Dance with Dragons (A Song of Ice and Fire)   
6   A Game of Thrones / A Clash of Kings / A Storm...   
7                      A Gentleman in Moscow: A Novel   
8       A Higher Loyalty: Truth, Lies, and Leadership   
9                           A Man Called Ove: A Novel   
10                          A Man Called Ove: A Novel   

                      Author  
0                   JJ Smith  
1               Stephen King  
2         Jordan B. Peterson  
3              George Orwell  
4   National Geographic Kids  
5        George R. R. Martin  
6        George R. R. Martin  
7                Amor Towles  
8                James Comey  
9            Fredrik Backman  
10           Fredrik Backman

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
arr = np.array([13, 6, 3, 5, 10])

In [21]:
np.argmax(arr)

0