In [1]:
import numpy as np

In [2]:
arr=np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [3]:
cond = arr>5
cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
arr_1=arr[(arr>5)&(arr<9)]
arr_1

array([6, 7, 8], dtype=int8)

In [5]:
arr_1

array([6, 7, 8], dtype=int8)

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [20]:
arr[arr>5]=20

In [21]:
arr

array([ 1,  2,  3,  4,  5, 20, 20, 20, 20, 20], dtype=int8)