In [1]:
import numpy as np


In [2]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
troz_arr=arr[0:6]
troz_arr

array([0, 1, 2, 3, 4, 5])

In [4]:
troz_arr[:]=50

In [5]:
arr

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9])

In [6]:
arr_copy=arr.copy()

In [7]:
troz_arr=arr_copy[0:6]
troz_arr[:]=100

In [8]:
arr

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9])

In [9]:
troz_arr

array([100, 100, 100, 100, 100, 100])