In [1]:
import numpy as np

In [2]:
range(0,10)

range(0, 10)

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.array(list(range(0,10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(4,4)

array([[0.23014264, 0.63652639, 0.04231303, 0.79530921],
       [0.37219102, 0.95055697, 0.58068696, 0.54310911],
       [0.3032751 , 0.34997859, 0.7115976 , 0.23902548],
       [0.70328009, 0.71142083, 0.20245432, 0.85588446]])

In [21]:
np.random.randint(1,15)

7

In [22]:
np.random.randint(1,100,(10,10))

array([[29, 12, 26, 59, 39, 95, 96, 50, 68,  6],
       [67, 94, 35, 82, 13, 70, 93, 39, 63, 68],
       [78, 88,  7, 34, 42, 18, 31, 10, 31, 63],
       [77, 59,  3, 21, 42, 36, 22, 60, 35, 69],
       [25,  4, 89, 61,  4, 46, 97,  1, 98, 35],
       [57,  5, 87, 18, 78, 46, 38, 16,  6, 44],
       [50, 65,  4, 30, 85, 23, 77, 37, 23,  7],
       [84, 52, 82, 89,  8, 59, 45, 52, 86, 96],
       [28, 38, 14, 96, 14, 98, 52, 26, 12, 48],
       [95, 19, 98, 88, 28, 19, 29, 10, 84, 64]])