In [1]:
import numpy as np

In [12]:
arr=np.random.randint(1,20,10)
arr
#print(arr)

array([ 3,  4, 18, 11, 15, 11, 19,  2, 15,  3])

In [11]:
matriz=arr.reshape(2,5)
matriz
#print(matriz)

array([[12,  5, 10,  1,  4],
       [ 8,  1,  2,  9,  3]])

In [13]:
arr.max()

19

In [16]:
matriz.max(0)

array([12,  5, 10,  9,  4])

In [18]:
matriz.argmax(0)

array([0, 0, 0, 1, 0])

In [19]:
matriz.argmax(1)

array([0, 3])

In [22]:
np.percentile(arr,100)

19.0

In [21]:
np.percentile(matriz,50)

4.5

In [24]:
arr.sort()
arr

array([ 2,  3,  3,  4, 11, 11, 15, 15, 18, 19])

In [25]:
matriz.sort()
matriz

array([[ 1,  4,  5, 10, 12],
       [ 1,  2,  3,  8,  9]])

In [26]:
np.median(arr)

11.0

In [28]:
np.median(matriz,1)

array([5., 3.])

In [32]:
np.std(arr)**2

39.489999999999995

In [31]:
np.var(arr)

39.489999999999995

In [33]:
np.mean(arr)

10.1

In [35]:
a=np.array([[1,2],[3,4]])
b=np.array([5,6])
print(a.ndim)
print(b.ndim)
b=np.expand_dims(b,axis=0)
np.concatenate((a,b),axis=0)

2
1


array([[1, 2],
       [3, 4],
       [5, 6]])