In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,(2,3))
print(arr)

[[8 7 2]
 [2 1 2]]


In [3]:
arr.reshape(3,2)

array([[8, 7],
       [2, 2],
       [1, 2]])

In [4]:
arr.shape

(2, 3)

In [5]:
np.reshape(arr,(3,2))

array([[8, 7],
       [2, 2],
       [1, 2]])

In [6]:
np.reshape(arr,(2,3),'C')

array([[8, 7, 2],
       [2, 1, 2]])

In [7]:
np.reshape(arr,(2,3),'F')

array([[8, 7, 2],
       [2, 1, 2]])